### ISSUE TITLE
Exported Sedumi .mat isn't working, Matlab errors during read_sedumi command of SDPT3solve.m

### ISSUE THREAD

**Issue by TrishGillett** [TrishGillett/pysdpt3glue#4]

**Comment by TrishGillett** [comment]
Note: When using NEOS, this problem manifests as a Matlab output message that only has the header.  For example, from unittest_neos.py:

``` ======================================================================
FAIL: test_min (__main__.TestBlackbox)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/trish/py-sdpt3-glue/unittest_neos.py", line 86, in test_min
    result = slv.sdpt3_solve(problem, 'neos', matfile_target, output_target=output_target)
  File "/Users/trish/py-sdpt3-glue/solve.py", line 50, in sdpt3_solve
    result = res.make_result_dict(msg)
  File "/Users/trish/py-sdpt3-glue/result.py", line 13, in make_result_dict
    assert can_use_msg(msg), "Stopping, the message is not properly formed: " + msg
AssertionError: Stopping, the message is not properly formed:
```

```
                            < M A T L A B (R) >
                  Copyright 1984-2016 The MathWorks, Inc.
                   R2016a (9.0.0.341360) 64-bit (glnxa64)
                             February 11, 2016


For online documentation, see http://www.mathworks.com/support
For product information, visit www.mathworks.com.


    Academic License

>> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> >> 

******
```

**Comment by TrishGillett** [comment]
Here's an example of something that fails.  If we can figure out why, that should tell us what the problem is.

```
def failing_example(folder, mode):
    '''
    Set up the data for two cases of b (0 or nonzero) and two cases of 'f' (2 or 6)
    '''
    A = 1.*np.array([[1, 0, 0, 0], # X00 = 1
                     [0, 0, 0, 1]]) # X11 = 1
    b = 1.*np.array([1, 1]).reshape(2, 1)
    c = 1.*np.array([0, 1, 0, 0]).reshape(1, 4)
    K = {'l': 0, 's': [2]}

    matfile_target = os.path.join(folder, 'matfile.mat')
    output_target = os.path.join(folder, 'output.txt')
    sw.write_sedumi_to_mat(A, b, c, K, matfile_target)
    result = slv.sdpt3_solve_mat(matfile_target,
                                 mode,
                                 output_target=output_target,
                                 discard_matfile=False)

    return result

folder = 'temp' # Where to save the .mat and output log.  
mode = 'neos' # Choose neos, matlab, or octave (octave is VERY beta, expect it to crash and burn)
failing_example(folder, mode)
```

**Comment by TrishGillett** [comment]
Another possible NEOS error is

```
You chose the SDPT3 solver.
ERROR: The input file was not provided.

Please correct and resubmit.
```

Be wary, this can mean that a file was provided but Matlab errored during the
`[blk,At,C,b] = read_sedumi(in_file);`
step, which is what is happening.

**Comment by TrishGillett** [comment]
That last comment was wrong, that error was in fact due to issue #5, now fixed.

**Comment by TrishGillett** [comment]
When SDPT3 errors, the detailed error isn't printed in the returned log.  However, it can be seen on the loading page in browser before the log file loads.  Here's the one for unittest_neos' test_submission():

```
*************************************************************

   NEOS Server Version 5.0
   Job#     : 4444088
   Password : efgWChtu

   Disclaimer:

   This information is provided without any express or
   implied warranty. In particular, there is no warranty
   of any kind concerning the fitness of this
   information  for any particular purpose.

   PLEASE DO NOT RELOAD THIS PAGE.
*************************************************************
Running:
(blah blah)

Queued:
(blah blah)

Job 4444088 submitted to neos.la.asu.edu
password: efgWChtu
---------- Begin Solver Output -----------
Executing /home/neos6/bin/solve_sdpt3
Checking the input file 
Error: { Undefined function 'sparse' for input arguments of type 'int64'.
Error: 
Error: Error in read_sedumi (line 169)
Error:          Avec{idxblk,1} = sparse(len,m);
Error: } 
Error: { Undefined function or variable 'b'.
Error: } 
Error: { Undefined function or variable 'blk'.
Error: } 
Error: { Undefined function or variable 'm'.
Error: } 
Calling solver: 'SDPT3'
Error: { Undefined function or variable 'blk'.
Composing results
Error: }  
Error: { Undefined function or variable 'X'.
Error: } 
Error: { Undefined function or variable 'y'.
Error: } 
Error: { Undefined function or variable 'Z'.
Error: } 
Error: /bin/rm: cannot remove â€˜comm*â€™: No such file or directory
```

**Comment by TrishGillett** [comment]
Problem identified!  It works if the numbers in K are recast to be floating point numbers.
- [x] Input sanitization needs to happen in sedumi_writer.write_sedumi_to_mat.
- [x] Check if s takes a list/tuple of one as well as an int.
- [x] Remove the skip decorators and try all tests.
- [x] Add a unittest for the sanitization method.
